lambda ::=


value  ::= num | string | expr | list | dict
num    ::= \d(.\d+)?
string ::= \".*\"|\'.*\' --escape "\"
list   ::= "[" value ("," value) "]"
dict   ::= "{" dict_pair (";" dict_pair) "}"
dict_pair ::= symbol ": " value
symbol ::= \w[\w\d-?!_.:]*
expr   ::= symbol(\s+ symbol)*
